import {
  StateGraph,
  START,
  END,
  Annotation,
  MemorySaver,
} from "@langchain/langgraph";

import {
  HumanMessage,
  SystemMessage,
  AIMessage,
  type BaseMessage,
} from "@langchain/core/messages";

import { z } from "zod";

import { LLMFactory } from "../llm/llm.factory";
import { ProductService } from "../../services/product-lookup.service";
import { PredictionService } from "../../services/prediction.service";

// ============================================================
// Dependencies
// ============================================================

const checkpointer = new MemorySaver();

const productService = new ProductService();

const predictionService = new PredictionService();

const responseLLM = LLMFactory.create();

// ============================================================
// Request extraction schema
// ============================================================

const RequestSchema = z.object({
  action: z.enum(["forecast", "unknown"]),

  productName: z.string().nullable(),

  months: z.number().int().positive().nullable(),

  promotionFlag: z.boolean().nullable(),

  holidayFlag: z.boolean().nullable(),

  discountPct: z.number().min(0).max(100).nullable(),
});

const parser = LLMFactory.create().withStructuredOutput(RequestSchema);

// ============================================================
// Graph State
// ============================================================

const InventoryState = Annotation.Root({
  messages: Annotation<BaseMessage[]>({
    reducer: (current, update) => current.concat(update),

    default: () => [],
  }),

  action: Annotation<"forecast" | "unknown">({
    reducer: (_, update) => update,
    default: () => "unknown",
  }),

  productName: Annotation<string | null>({
    reducer: (_, update) => update,
    default: () => null,
  }),

  productId: Annotation<string | null>({
    reducer: (_, update) => update,
    default: () => null,
  }),

  storeId: Annotation<string | null>({
    reducer: (_, update) => update,
    default: () => null,
  }),

  months: Annotation<number | null>({
    reducer: (_, update) => update,
    default: () => null,
  }),

  promotionFlag: Annotation<boolean | null>({
    reducer: (_, update) => update,
    default: () => null,
  }),

  holidayFlag: Annotation<boolean | null>({
    reducer: (_, update) => update,
    default: () => null,
  }),

  discountPct: Annotation<number | null>({
    reducer: (_, update) => update,
    default: () => null,
  }),

  result: Annotation<unknown | null>({
    reducer: (_, update) => update,
    default: () => null,
  }),

  error: Annotation<string | null>({
    reducer: (_, update) => update,
    default: () => null,
  }),
});
function normalizeProductName(
  value: string | null
): string | null {
  if (!value) {
    return null;
  }

  const normalized = value.trim();

  const invalidValues = [
    "unknown",
    "null",
    "none",
    "not provided",
    "n/a",
  ];

  if (
    invalidValues.includes(
      normalized.toLowerCase()
    )
  ) {
    return null;
  }

  // Store IDs are not product names
  if (/^S\d{3}$/i.test(normalized)) {
    return null;
  }

  // Product IDs are handled separately
  if (/^P\d{4}$/i.test(normalized)) {
    return null;
  }

  return normalized;
}
// ============================================================
// Parse User Request
// ============================================================

async function parseRequestNode(state: typeof InventoryState.State) {
  const lastHumanMessage = [...state.messages]
    .reverse()
    .find((message) => message instanceof HumanMessage);

  if (!lastHumanMessage) {
    return {
      error: "No user message found.",
    };
  }

  const text =
    typeof lastHumanMessage.content === "string"
      ? lastHumanMessage.content
      : "";

  /*
   * Internal IDs should NOT be generated by the LLM.
   *
   * If user explicitly gives:
   *
   * P0002
   * S010
   *
   * we can safely extract them from the actual user message.
   */

  const explicitProductId = text.match(/\bP\d{4}\b/i)?.[0]?.toUpperCase();

  const explicitStoreId = text.match(/\bS\d{3}\b/i)?.[0]?.toUpperCase();

  /*
   * LLM is only responsible for understanding
   * natural language values.
   */

const parsed = await parser.invoke(`
Extract ONLY information explicitly provided by the user.

If a value is not provided, return null.

Do NOT return:
- "unknown"
- "none"
- "not provided"
- identifiers like S010 as productName

Do not choose defaults.
Do not invent missing values.

Examples:

"for product Curd"
productName = Curd

"6 months"
months = 6

"with 10% discount"
discountPct = 10

"during holiday with promotion"
holidayFlag = true
promotionFlag = true

"without promotion"
promotionFlag = false
Request:
${text}
`);

const parsedProductName =
  normalizeProductName(
    parsed.productName
  );

  /*
   * IMPORTANT:
   *
   * Only update state fields that the user supplied.
   *
   * This allows conversation memory:
   *
   * Turn 1:
   * Forecast Curd for S010
   *
   * Turn 2:
   * 6 months
   *
   * product/store stay in state.
   */

  const update: Partial<typeof InventoryState.State> = {
    // previous forecast result should not be reused
    result: null,

    // clear previous error
    error: null,
  };

  if (parsed.action !== "unknown") {
    update.action = parsed.action;
  }

  /*
   * Explicit product ID supplied by user
   */
    if (explicitProductId) {
    update.productId =
        explicitProductId;

    update.productName = null;
    }
    else if (parsedProductName !== null) {
    update.productName =
        parsedProductName;

    // New product name means old ID
    // is no longer valid.
    update.productId = null;
    }

  if (explicitStoreId) {
    update.storeId = explicitStoreId;
  }

  if (parsed.months !== null) {
    update.months = parsed.months;
  }

  if (parsed.promotionFlag !== null) {
    update.promotionFlag = parsed.promotionFlag;
  }

  if (parsed.holidayFlag !== null) {
    update.holidayFlag = parsed.holidayFlag;
  }

  if (parsed.discountPct !== null) {
    update.discountPct = parsed.discountPct;
  }

  return update;
}

// ============================================================
// Required Field Validation
// ============================================================

function getMissingForecastField(state: typeof InventoryState.State) {
  if (!state.productId && !state.productName) {
    return "product";
  }

  if (!state.storeId) {
    return "store";
  }

  if (!state.months) {
    return "months";
  }

  return null;
}

// ============================================================
// Routing
// ============================================================

function routeForecast(state: typeof InventoryState.State) {
  if (state.error) {
    return "finalAnswer";
  }

  /*
   * Product name exists but ID hasn't
   * been resolved yet.
   */
  if (!state.productId && state.productName) {
    return "lookupProduct";
  }

  const missing = getMissingForecastField(state);

  if (missing) {
    return "askMissingInfo";
  }

  return "forecast";
}

// ============================================================
// Ask Missing Required Information
// ============================================================

async function askMissingInfoNode(state: typeof InventoryState.State) {
  if (!state.productId && !state.productName) {
    return {
      messages: [new AIMessage("Which product would you like to forecast?")],
    };
  }

  if (!state.storeId) {
    return {
      messages: [new AIMessage("Which store would you like to forecast for?")],
    };
  }

  if (!state.months) {
    return {
      messages: [
        new AIMessage("For how many months would you like the forecast?"),
      ],
    };
  }

  return {};
}

// ============================================================
// Product Lookup
// ============================================================

async function lookupProductNode(state: typeof InventoryState.State) {
  if (!state.productName) {
    return {
      error: "Product name is missing.",
    };
  }

  try {
    const products = await productService.findByName(state.productName);

    if (!products.length) {
      return {
        error: `No product found for "${state.productName}".`,
      };
    }

    if (products.length > 1) {
      return {
        error: `Multiple products matched "${state.productName}". Please specify the product.`,
      };
    }

    return {
      productId: products[0].productId,
    };
  } catch (error) {
    return {
      error: error instanceof Error ? error.message : "Product lookup failed.",
    };
  }
}

// ============================================================
// Forecast
// ============================================================

async function forecastNode(state: typeof InventoryState.State) {
  /*
   * This node should only execute after
   * required validation succeeds.
   *
   * Still keep defensive checks.
   */

  if (!state.productId) {
    return {
      error: "Product ID is missing.",
    };
  }

  if (!state.storeId) {
    return {
      error: "Store ID is missing.",
    };
  }

  if (!state.months) {
    return {
      error: "Forecast duration is missing.",
    };
  }

  try {
    const result = await predictionService.forecast({
      productId: state.productId,

      storeId: state.storeId,

      months: state.months,

      /*
       * Optional parameters:
       *
       * User value if supplied,
       * otherwise business default.
       */

      promotionFlag: state.promotionFlag ?? false,

      holidayFlag: state.holidayFlag ?? false,

      discountPct: state.discountPct ?? 0,
    });

    return {
      result,
      error: null,
    };
  } catch (error) {
    return {
      error:
        error instanceof Error ? error.message : "Forecast service failed.",

      result: null,
    };
  }
}

// ============================================================
// Final Response
// ============================================================

async function finalAnswerNode(state: typeof InventoryState.State) {
  if (state.error) {
    return {
      messages: [new AIMessage(state.error)],
    };
  }

  const response = await responseLLM.invoke([
    new SystemMessage(`
You are IntelliStock AI.

Summarize only the supplied backend forecast result.

Do not invent numbers.
Do not modify forecast values.
`),

    new HumanMessage(`
Product:
${state.productName ?? state.productId}

Product ID:
${state.productId}

Store ID:
${state.storeId}

Forecast duration:
${state.months} months

Promotion:
${state.promotionFlag ?? false}

Holiday:
${state.holidayFlag ?? false}

Discount:
${state.discountPct ?? 0}%

Backend forecast result:

${JSON.stringify(state.result, null, 2)}
`),
  ]);

  return {
    messages: [response],
  };
}

// ============================================================
// Graph
// ============================================================

const graph = new StateGraph(InventoryState)

  .addNode("parseRequest", parseRequestNode)

  .addNode("lookupProduct", lookupProductNode)

  .addNode("askMissingInfo", askMissingInfoNode)

  .addNode("forecast", forecastNode)

  .addNode("finalAnswer", finalAnswerNode)

  // START -> parse
  .addEdge(START, "parseRequest")

  /*
   * After parsing:
   *
   * lookupProduct
   * askMissingInfo
   * forecast
   * finalAnswer
   */
  .addConditionalEdges("parseRequest", routeForecast)

  /*
   * Product lookup doesn't mean we're
   * ready to forecast.
   *
   * We must validate store/months again.
   */
  .addConditionalEdges("lookupProduct", routeForecast)

  /*
   * Missing field question ends this turn.
   *
   * Next user message with same thread_id
   * resumes with previous state.
   */
  .addEdge("askMissingInfo", END)

  .addEdge("forecast", "finalAnswer")

  .addEdge("finalAnswer", END);

// ============================================================
// Compile
// ============================================================

export const inventoryGraph = graph.compile({
  checkpointer,
});
